server:
  port: 3000

db:
  type: 'postgres'
  port: 5432
  database: 'forexmanagement'
  username: 'postgres'
  password: 'admin123'
  synchronize: true

jwt:
  expiresIn: 3600
  secret: "HelloFromTesting"